### PR TITLE
Allow to pass search terms in command

### PR DESCRIPTION
**Pull request by jstriebel**
This PR allows to use the command `venus cars hills`, which will search for those terms, overwriting anything that is specified in the config. If nothing is supplied everything stays as before. This is helpful when using venus interactively and not via a cronjob. Thanks for considering this change.

### CODE REVIEW

**Comment by AlfredoSequeida** [comment]
I can see this being helpful. Document the change in the README file and I will approve the request.

**Comment by jstriebel** [comment]
> I can see this being helpful. Document the change in the README file and I will approve the request.

@AlfredoSequeida Great, thanks! I updated the Readme accodingly.

**Comment by jstriebel** [comment]
@AlfredoSequeida Friendly ping :-)

**Comment by AlfredoSequeida** [comment]
@jstriebel Thank you for the ping. I apologize for not getting to it earlier, I've had a busy week. Thank you for your contribution!

**Pull request merged**
