### PR TITLE
Add Max Files option

### PR DESCRIPTION
**Pull request by coma-toast**
When I first started using this, I set it to 1 minute. That added like 6000 files to the storage directory after a long weekend. I changed it to 15 minutes to reduce that but adding a feature to limit the number of files is a good idea. You can customize how many files to keep in case you like one and want to go back later and save it somewhere permanently.

### CODE REVIEW

**Comment by AlfredoSequeida** [comment]
Great idea! I'll take a look at the code and return with an update.

**Comment by AlfredoSequeida** [comment]
Ok, so I got an error:

`Traceback (most recent call last):
  File "/usr/bin/venus", line 11, in <module>
    load_entry_point('venuspy==1.0.2', 'console_scripts', 'venus')()
  File "/usr/lib/python3.8/site-packages/venus/venus.py", line 86, in main
    cacheFiles = glob.glob(output_path_config+"/*")
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
`

This is happening because `output_path_config` gets set to None by default on line 71 if the user does not choose to have a directory to save the files to, which results in the files being saved in the temporary (tmp) directory.

After you fix that we should be good, at a quick glance everything else looks great!

**Comment by coma-toast** [comment]
Added an `and` to the if statement so it only runs if the `output_path_config` is set.

**Comment by AlfredoSequeida** [comment]
Awesome! Looks good! I'll go ahead and mearge the change. Thank you for your work!

**Pull request merged**
